Feature
BenjaminGarza/Enumerable-Methods pull request #1
Opened 2019-08-21 21:45 UTC by BenjaminGarza

2019-08-22 20:56 UTC, bellom requested changes
Hi @BenjaminGarza 
Great work using `Git Flow`, just two methods to work on and move to the next project, kindly work on the following methods, they seems not working, read more on my comments;
1 `my_count`
2 `my_inject`

_Kindly re-submit for review after making all those changes slightly_smiling_face Thumps -up await you._

2019-08-22 20:56 UTC, bellom commented on Enumerables.rb
> +      count += 1 if block.call(element) == true
`my_count` seems not working, you need to work on it, got two errors stated below while running the method.
```
     NoMethodError:
       undefined method `call' for nil:NilClass
```
```
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```

2019-08-22 20:56 UTC, bellom commented on Enumerables.rb
> +  def my_inject(result, &block)
`my_inject` seems not working, you need to work on it, got the below while running the method.
```
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```

2019-08-26 15:13 UTC, BenjaminGarza commented on Enumerables.rb
> +      count += 1 if block.call(element) == true
Please share the code you used to get that error, my test case returns the expected result so I cannot debug it without your test case

2019-08-26 15:14 UTC, BenjaminGarza commented on Enumerables.rb
> +  def my_inject(result, &block)
Please share your test case

2019-08-26 22:44 UTC, BenjaminGarza commented on Enumerables.rb
> +      count += 1 if block.call(element) == true
My_count would not work without a block, it is now fixed, thank you

2019-08-27 23:15 UTC, jofer86 requested changes
## :clap: :clap: Great job Benjamin!!, Just a couple of :bug: found on your code, those are adressed down in the comments, please see to it and work some fixes on those bugs, and ask for a new review
Cheers!

2019-08-27 23:15 UTC, jofer86 commented on Enumerables.rb
> +    if block_given? == true
## O noes!! there is a :bug: here, time to squash it!!
This part of your code is not replicating the behavior of the original count method, while it now works with a block and an argument, is not working when the method is passed on its own that is, like this : [1,2,3,4,5].my_count there we get an argument error. Please do squash that nasty bug .

2019-08-27 23:15 UTC, jofer86 commented on Enumerables.rb
> -    my_each do |element|
## Can you see it? Ohhh there it is!! :beetle: . A nasty bug, lets DDT it!!

In this case your Inject is returning an argument error when we pass a block, apparently, all it wants is arguments!.
Lets fix that so that your code is able to recieve a block also!.

2019-08-31 01:45 UTC, maelfosso requested changes
Hello @BenjaminGarza 

Nice improvement !!!
You are about to finish that project.
Please, take a look on the below to understand the bug to fix.
Make the corresponding changes and re-submit the code review request.

Don't hesitate to message me on Slack if you have any question.

2019-08-31 01:45 UTC, maelfosso commented on Enumerables.rb
>    end
Please there is still a bug in `my_inject` method.
Let me share with you what I get when testing it
```ruby
irb(main):014:0> [5,6,7,8,9,10].inject {|sum, n| sum + n }
=> 45
irb(main):015:0> [5,6,7,8,9,10].my_inject {|sum, n| sum + n }
=> 45
irb(main):016:0> [5,6,7,8,9,10].inject(5) {|sum, n| sum + n }
=> 50
irb(main):017:0> [5,6,7,8,9,10].my_inject(5) {|sum, n| sum + n }
Traceback (most recent call last):
        3: from /home/elvisfosso/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        2: from (irb):17
        1: from Enumerables.rb:83:in `my_inject'
ArgumentError (wrong number of arguments (given 1, expected 0))
irb(main):002:0> [5,6,7,8,9,10].my_inject { |product, n| product * n }
=> 151200
irb(main):003:0> [5,6,7,8,9,10].inject { |product, n| product * n }
=> 151200
irb(main):004:0> [5,6,7,8,9,10].inject(1) { |product, n| product * n }
=> 151200
irb(main):005:0> [5,6,7,8,9,10].my_inject(1) { |product, n| product * n }
Traceback (most recent call last):
        3: from /home/elvisfosso/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        2: from (irb):5
        1: from Enumerables.rb:83:in `my_inject'
ArgumentError (wrong number of arguments (given 1, expected 0))
irb(main):006:0> 
```

2019-08-31 01:45 UTC, maelfosso commented on Enumerables.rb
> +  end
Ooo sorry, still a bug to fix
Take a look of that result, please
```ruby
irb(main):007:0> ary = [1,2,3,2]
=> [1, 2, 3, 2]
irb(main):008:0> ary.count
=> 4
irb(main):009:0> ary.my_count
=> 4
irb(main):010:0> ary.count(2)
=> 2
irb(main):011:0> ary.my_count(2)
Traceback (most recent call last):
        3: from /home/elvisfosso/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        2: from (irb):11
        1: from Enumerables.rb:61:in `my_count'
ArgumentError (wrong number of arguments (given 1, expected 0))
irb(main):012:0> ary.count { |x| x%2 == 0 }
=> 2
irb(main):013:0> ary.my_count { |x| x%2 == 0 }
=> 2
```

2019-09-02 22:49 UTC, bolah2009 approved these changes
# Nice Job implementing the suggested changes...

Tested all methods with built-in methods and works fine. Looks good to me...:+1:

Please take note of Git Flow in your next project

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-09-05 22:44 UTC, merged